const RENDERER_TYPE_MAP = {
  MULTIPLE_CHOICE: "MCQ",
  TRUE_FALSE_NOT_GIVEN: "TFNG",
  YES_NO_NOT_GIVEN: "YES_NO_NOTGIVEN",
  MATCHING_HEADING: "MATCHING",
  MATCHING_INFORMATION: "MATCHING",
  MATCHING_FEATURES: "MATCHING",
  MATCHING_SENTENCE_ENDINGS: "MATCHING",
  SENTENCE_COMPLETION: "FILL_BLANK",
  SUMMARY_COMPLETION: "FILL_BLANK",
  NOTE_COMPLETION: "FILL_BLANK",
  TABLE_COMPLETION: "FILL_BLANK",
  FLOW_CHART_COMPLETION: "FILL_BLANK",
  DIAGRAM_LABELING: "LABELING",
  SHORT_ANSWER: "SHORT_ANSWER",
  MCQ: "MCQ",
  TFNG: "TFNG",
  YES_NO_NOTGIVEN: "YES_NO_NOTGIVEN",
  MATCHING: "MATCHING",
  FILL_BLANK: "FILL_BLANK",
  LABELING: "LABELING",
  OTHER: "SHORT_ANSWER",
};

export const mapBackendTypeToRendererType = (typeQuestion) => {
  if (!typeQuestion) {
    return "SHORT_ANSWER";
  }

  return RENDERER_TYPE_MAP[typeQuestion] || "SHORT_ANSWER";
};
