export const TICKETS = [
  {
    id: "a31f8c20",
    type: "WRITING",
    student: "Nguyễn Minh Anh",
    test: "Cambridge 18 - Test 2",
    aiBand: 6.5,
    status: "PENDING",
    date: "2026-05-31",
  },
  {
    id: "b7d4e918",
    type: "SPEAKING",
    student: "Trần Văn Hùng",
    test: "IELTS Speaking Mock 4",
    aiBand: 5.5,
    status: "PENDING",
    date: "2026-05-31",
  },
  {
    id: "c9a02f31",
    type: "WRITING",
    student: "Lê Thu Hà",
    test: "Cambridge 17 - Test 1",
    aiBand: 7.0,
    status: "PENDING",
    date: "2026-05-30",
  },
  {
    id: "d2e51b88",
    type: "WRITING",
    student: "Phạm Quốc Bảo",
    test: "Academic Writing Set A",
    aiBand: 6.0,
    status: "CLAIMED",
    date: "2026-05-30",
    teacher: "You",
  },
  {
    id: "e8f73a45",
    type: "SPEAKING",
    student: "Đỗ Mai Chi",
    test: "IELTS Speaking Mock 2",
    aiBand: 6.5,
    status: "IN_PROGRESS",
    date: "2026-05-29",
    teacher: "You",
  },
  {
    id: "b8e21c47",
    type: "WRITING",
    student: "Ngô Khánh Linh",
    test: "Cambridge 15 - Test 4",
    aiBand: 6.5,
    status: "IN_PROGRESS",
    date: "2026-05-28",
    teacher: "You",
  },
  {
    id: "f1c64d27",
    type: "WRITING",
    student: "Vũ Đức Long",
    test: "Cambridge 16 - Test 3",
    aiBand: 5.5,
    teacherBand: 6.0,
    status: "COMPLETED",
    date: "2026-05-28",
    teacher: "You",
    commission: 50000,
  },
  {
    id: "a0b95e63",
    type: "SPEAKING",
    student: "Hoàng Lan",
    test: "IELTS Speaking Mock 1",
    aiBand: 6.0,
    teacherBand: 6.5,
    status: "COMPLETED",
    date: "2026-05-27",
    teacher: "You",
    commission: 40000,
  },
];
